# Generated by Django 4.1.6 on 2023-04-07 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('mmcy_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('onenote_link', models.URLField(blank=True, null=True)),
                ('resource_model', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_description', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=150)),
                ('estimation', models.CharField(max_length=50, null=True)),
                ('total_hour', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('first_draft_date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataManagement.client')),
                ('members', models.ManyToManyField(to='userManagement.employee')),
            ],
        ),
    ]
