# Generated by Django 4.1.6 on 2023-04-07 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_name', models.CharField(max_length=100)),
                ('project_required', models.BooleanField(default=True)),
                ('description_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DateRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('ending_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CriterionMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify', models.BooleanField(default=False)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditManagement.measurement')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditManagement.criterion')),
            ],
        ),
        migrations.CreateModel(
            name='AccountManagerAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('added_at', models.DateTimeField(auto_now=True)),
                ('notice', models.BooleanField(default=False)),
                ('text_description', models.TextField(blank=True, null=True)),
                ('image_uploaded', models.ImageField(blank=True, upload_to='screenshot/')),
                ('auditives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditee', to='userManagement.employee')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditManagement.criterionmeasurement')),
            ],
        ),
    ]
