# Generated by Django 4.1.6 on 2023-04-07 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditManagement', '0001_initial'),
        ('dataManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmanageraudit',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataManagement.project'),
        ),
    ]
